
import { ClerkProvider } from '@clerk/nextjs'
import { Silkscreen } from 'next/font/google' // Using Silkscreen
import './globals.css'
import { Providers } from './providers'
import { SiteNavbar } from './_components/navbar'

export const silkScreen = Silkscreen({
  subsets: ["latin"],
  weight: "400",
});

// This is now fine because the file is a Server Component
// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // Wrap the entire layout with ClerkProvider if you want it to cover all routes
  return (
    <ClerkProvider>
      <html lang="en" className={silkScreen.className}>
        <body>
          <SiteNavbar />
          
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}