import { Silkscreen } from 'next/font/google' // Using Silkscreen
import './globals.css'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <html lang="en" >
        <body>
          
            {children}
        </body>
      </html>
  );
}