import { Silkscreen } from 'next/font/google' // Using Silkscreen
import './globals.css'

const silkScreen = Silkscreen({
  subsets: ["latin"],
  weight: "400",
});

// This is now fine because the file is a Server Component
// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <html lang="en" className={silkScreen.className}>
        <body>
          
            {children}
        </body>
      </html>
  );
}